language: java
jdk:
- oraclejdk7
- openjdk6
- oraclejdk8
branches:
  except:
  - www
cache:
  apt: true
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
before_install:
- sudo apt-get -q update
- sudo apt-get -q install --no-install-recommends pandoc python-pandas
- pip install --user pandocfilters
- git fetch --depth=10000 origin
install: ./gradlew ciPrep
script: ./gradlew ciTest
env:
  global:
  - TERM=dumb
  - TZ=CST6CDT
