language: java
jdk:
- oraclejdk7
- openjdk6
- oraclejdk8
branches:
  except:
  - www
cache:
  apt: true
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
before_install:
- sudo apt-get -q update
- sudo apt-get -q install --no-install-recommends pandoc python-pandas
- pip install --user pandocfilters
- git fetch --depth=10000 origin
install: ./gradlew ciPrep
script: ./gradlew ciBuild
env:
  global:
  - TERM=dumb
  - TZ=CST6CDT
  # DEPLOY_USER
  - secure: "QUz7X25DVKDZic9H2gGOvsCREtSYPxz01eQgCrGOmq1Ad0z1xMq7BvppvqL4mSOqnGG3OW5zddNf1qn/dJAc6hP78ZwSqeKBXo8cuQzA/PsFb0OlKG+kCVM9b+lQQShCexDxsg5DVbnrewDwDOtSYvxbrnhgN0IjRUoHp92778A="
  # DEPLOY_PASSWORD
  - secure: "GbHF/yVGEmktYE6OLLdSoM5FQjwrVNhAPNQNhiu60Mrcs8e1v3DXR3oOTg0FIvIxW9u5fjh4HlnGJbZirDV+7DSgN0dRofzIc4DS3ciwtl+24ro8D/yBBNKROJqG73gv7nNH5MIcJXhSqtpzjt8STshPskDOqy1qsMpwbycxEVw="
  # DEPLOY_KEY_PASSPHRASE
  - secure: "OEZs5MnIlhRaonxYs/Wgwrni1rE5zrJ2h+ifLZzsjVtAwTCjnUFgBS7K4/3EsBfQpNQFOa0ANu5c/MHvWXM6bPVGGF4zL2tDsEizdilaTbUUKB1X8CZMPQw7Dobdg129xaLbaFb5TjzvDjwAeJGeyMrNSWQkeLKL42O0YsYwgVs="
